# Generated by Django 5.2.8 on 2025-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for single-day events.', null=True),
        ),
    ]
