# Generated by Django 5.2.8 on 2025-11-17 14:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('material', 'Material'), ('maintenance', 'Maintenance'), ('salary', 'Salary'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='finance_exp_date_677539_idx'), models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Card')], max_length=20)),
                ('txn_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='finance/receipts/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='students.student')),
            ],
            options={
                'verbose_name': 'Fees Receipt',
                'verbose_name_plural': 'Fees Receipts',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['receipt_no'], name='finance_fee_receipt_d0a6c0_idx'), models.Index(fields=['date'], name='finance_fee_date_629e10_idx'), models.Index(fields=['mode'], name='finance_fee_mode_8521a0_idx'), models.Index(fields=['locked'], name='finance_fee_locked_a63af2_idx')],
            },
        ),
    ]
