# Generated by Django 5.2.8 on 2025-11-17 16:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('electricity', 'Electricity'), ('salary', 'Staff Salary'), ('materials', 'Materials/Supplies'), ('maintenance', 'Maintenance'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('txn_id', models.CharField(blank=True, help_text='Transaction ID for digital payments', max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='students.student')),
            ],
            options={
                'verbose_name': 'Fees Receipt',
                'verbose_name_plural': 'Fees Receipts',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['receipt_no'], name='finance_fee_receipt_d0a6c0_idx'), models.Index(fields=['date'], name='finance_fee_date_629e10_idx')],
            },
        ),
    ]
