# Generated by Django 5.2.8 on 2025-11-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_file',
        ),
    ]
