# Generated by Django 5.2.8 on 2025-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcertificate',
            name='certificate_no',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30, null=True),
        ),
    ]
